defaults:
  - /dataset: yaak/train
  # - /dataset: yaak/train_clip
  - _self_

_target_: torch.utils.data.DataLoader
batch_size: 32
shuffle: true
num_workers: 32
pin_memory: false
persistent_workers: true
multiprocessing_context: forkserver
collate_fn:
  _target_: rbyte.utils.dataloader.collate_identity
  _partial_: true
