visual:
  _target_: lerobot.configs.types.NormalizationMode
  _args_: ["IDENTITY"]
action:
  _target_: lerobot.configs.types.NormalizationMode
  _args_: ["MEAN_STD"]
state:
  _target_: lerobot.configs.types.NormalizationMode
  _args_: ["MEAN_STD"]
quantile_normalization:
  use_quantiles_instead_of_min_max: false
  quantile_keys_dims: ???
