data: /nasa/drives/yaak/data
rbyte:
  cache: .rbyte_cache_2
lerobot_stats_27: /nasa/drives/yaak/data/lerobot_metadata/dataset_stats_all_quantiles_flatten.json
lerobot_stats: /nasa/drives/yaak/data/lerobot_metadata/dataset_stats_rbyte_28.json